language: php

sudo: false

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: nightly
  allow_failures:
    - php: nightly
  fast_finish: true

before_install: composer self-update

install: composer install

before_script: mkdir -p build/logs

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script: vendor/bin/coveralls -v
